name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: gradle clean build
#       run: docker build . --file Dockerfile --tag vishalmamidi/demo-rest:$(date +%s)
